name: lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check files with .editorconfig
        run: |
          docker run --rm --volume=$PWD:/check mstruebing/editorconfig-checker ec -exclude \\.py$
          docker run --rm --volume=$PWD:/check mstruebing/editorconfig-checker ec -disable-indent-size -disable-max-line-length
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          python -m poetry -V
          python -m poetry config virtualenvs.create false
      - name: Install dependencies
        run: python -m poetry install
      - name: Check Python files with flake8
        run: |
          flake8 --version
          flake8 . --count --show-source --statistics
      - name: Check Python files with mypy
        run: |
          mypy --version
          mypy .
      - name: Check Python files with isort
        run: |
          isort --version
          isort . -c
